# Generated by Django 4.1.6 on 2023-02-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_ratingreview_rating_ratingreview_rating_range_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='watchList',
            new_name='watched',
        ),
    ]
